version: "2"
checks:
  method-complexity:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
  method-lines:
    config:
      threshold: 100
  argument-count:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 400
  method-count:
    config:
      threshold: 25
exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"

